"""Add relationship field to Response

Revision ID: 7908ba5b4553
Revises: d00b9b2a3aed
Create Date: 2025-02-20 22:07:21.657718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7908ba5b4553'
down_revision = 'd00b9b2a3aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###
