"""Add guest_status and table_number to Response

Revision ID: d00b9b2a3aed
Revises: 
Create Date: 2025-02-10 20:33:50.205494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00b9b2a3aed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('table_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('table_number')
        batch_op.drop_column('guest_status')

    # ### end Alembic commands ###
