"""Add relationship field to Response

Revision ID: e62c84731cd6
Revises: 7908ba5b4553
Create Date: 2025-02-20 22:15:27.002692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62c84731cd6'
down_revision = '7908ba5b4553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
